import 'package:supabase_flutter/supabase_flutter.dart';
import '../../domain/models/reservation.dart';
import '../../domain/repositories/reservation_repository.dart';

class SupabaseReservationRepository implements ReservationRepository {
  final SupabaseClient _supabaseClient;
  static const String tableName = 'reservations';

  SupabaseReservationRepository({SupabaseClient? client}) 
      : _supabaseClient = client ?? Supabase.instance.client;

  @override
  Future<Reservation> createReservation(Reservation reservation) async {
    // The id is usually generated by DB (UUID), so we might remove id from toJson if it's empty,
    // but assuming for this demo the model is created mostly locally and merged, or Supabase generates it.
    // If Supabase generates it, we don't pass 'id' if it's not set. 
    // Let's pass the JSON and let Supabase handle the exact merge or insert.
    final json = reservation.toJson();
    if (json['id'] == '' || json['id'] == null) {
      json.remove('id');
    }
    
    final response = await _supabaseClient
        .from(tableName)
        .insert(json)
        .select()
        .single();
        
    return Reservation.fromJson(response);
  }

  @override
  Future<List<Reservation>> getUserReservations(String profileId) async {
    final response = await _supabaseClient
        .from(tableName)
        .select('*, rooms(*, hotels(*))') // Fetching room and hotel relation if available in schema
        .eq('profile_id', profileId)
        .order('created_at', ascending: false);
        
    return (response as List).map((json) => Reservation.fromJson(json)).toList();
  }

  @override
  Future<Reservation?> getReservationById(String id) async {
    final response = await _supabaseClient
        .from(tableName)
        .select('*, rooms(*, hotels(*))')
        .eq('id', id)
        .maybeSingle();
        
    if (response == null) return null;
    return Reservation.fromJson(response);
  }

  @override
  Future<Reservation> updateReservationStatus(String id, String status) async {
    final response = await _supabaseClient
        .from(tableName)
        .update({'status': status})
        .eq('id', id)
        .select()
        .single();
        
    return Reservation.fromJson(response);
  }
}
